import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "primereact/resources/primereact.min.css";
import "primereact/resources/themes/luna-blue/theme.css";
import "bulma/css/bulma.css";
import "app/components/common/loader/loader.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Vendas App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
